-- MarketPulse Crypto Signals / Paper Trading
-- Run this once in Supabase SQL Editor.
-- IMPORTANT: n8n will later write scanner/monitoring data using a backend-only secret/service credential.

create table if not exists public.crypto_signals (
  id bigint generated by default as identity primary key,
  symbol text not null,
  direction text not null check (direction in ('LONG','SHORT')),
  timeframe text not null default '1h',
  quote text not null default 'USDT',
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  rr numeric not null default 2,
  score numeric not null default 0,
  confidence numeric,
  rsi numeric,
  atr numeric,
  volume_ratio numeric,
  reasons jsonb not null default '[]'::jsonb,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','TRIGGERED','EXPIRED','INVALIDATED')),
  source text not null default 'n8n',
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists crypto_signals_created_idx
  on public.crypto_signals(created_at desc);

create index if not exists crypto_signals_active_idx
  on public.crypto_signals(status, created_at desc);

create table if not exists public.crypto_trades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  signal_id bigint references public.crypto_signals(id) on delete set null,
  symbol text not null,
  direction text not null check (direction in ('LONG','SHORT')),
  timeframe text not null default '1h',
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  rr numeric not null default 2,
  amount_inr numeric not null default 0,
  leverage numeric not null default 1,
  status text not null default 'RUNNING'
    check (status in ('RUNNING','TP_HIT','SL_HIT','MANUAL','CANCELLED')),
  current_price numeric,
  pnl_inr numeric not null default 0,
  r_multiple numeric not null default 0,
  close_price numeric,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  notes text,
  updated_at timestamptz not null default now()
);

create index if not exists crypto_trades_user_idx
  on public.crypto_trades(user_id, opened_at desc);

create index if not exists crypto_trades_running_idx
  on public.crypto_trades(status, updated_at desc);

alter table public.crypto_signals enable row level security;
alter table public.crypto_trades enable row level security;

revoke all on table public.crypto_signals from anon;
revoke all on table public.crypto_trades from anon;

grant select on table public.crypto_signals to authenticated;
grant select, insert, update, delete on table public.crypto_trades to authenticated;

drop policy if exists "Authenticated users can read crypto signals" on public.crypto_signals;
create policy "Authenticated users can read crypto signals"
on public.crypto_signals
for select
to authenticated
using (true);

drop policy if exists "Users can read their crypto trades" on public.crypto_trades;
create policy "Users can read their crypto trades"
on public.crypto_trades
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their crypto trades" on public.crypto_trades;
create policy "Users can create their crypto trades"
on public.crypto_trades
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their crypto trades" on public.crypto_trades;
create policy "Users can update their crypto trades"
on public.crypto_trades
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their crypto trades" on public.crypto_trades;
create policy "Users can delete their crypto trades"
on public.crypto_trades
for delete
to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.set_crypto_trade_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists crypto_trades_updated_at on public.crypto_trades;
create trigger crypto_trades_updated_at
before update on public.crypto_trades
for each row execute function public.set_crypto_trade_updated_at();
