-- MarketPulse stock-data migration
-- DEV ONLY: central Supabase stock-data layer.
-- n8n should UPSERT stock_quotes every 30 seconds; it does not create
-- historical rows for every quote update.

create extension if not exists pgcrypto;

create table if not exists public.stocks (
  symbol text primary key,
  company_name text,
  exchange text not null default 'NSE',
  sector text,
  is_fno boolean not null default false,
  market_cap numeric,
  pe numeric,
  roe numeric,
  roce numeric,
  book_value numeric,
  face_value numeric,
  dividend_yield numeric,
  high_52w numeric,
  low_52w numeric,
  promoters_latest numeric,
  promoters_previous numeric,
  promoters_change numeric,
  source text default 'MarketPulse',
  updated_at timestamptz not null default now()
);

create index if not exists stocks_company_name_idx on public.stocks (company_name);
create index if not exists stocks_sector_idx on public.stocks (sector);
create index if not exists stocks_fno_idx on public.stocks (is_fno);

create table if not exists public.stock_quotes (
  symbol text primary key references public.stocks(symbol) on delete cascade,
  price numeric,
  previous_close numeric,
  open numeric,
  high numeric,
  low numeric,
  change numeric,
  change_percent numeric,
  high_52w numeric,
  low_52w numeric,
  source text not null default 'Yahoo Finance',
  quote_time timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists stock_quotes_updated_at_idx on public.stock_quotes (updated_at);
create index if not exists stock_quotes_quote_time_idx on public.stock_quotes (quote_time);

create table if not exists public.stock_fundamentals (
  id bigint generated by default as identity primary key,
  symbol text not null references public.stocks(symbol) on delete cascade,
  report_date date not null,
  revenue numeric,
  net_profit numeric,
  eps numeric,
  net_margin numeric,
  profit_before_tax numeric,
  net_worth numeric,
  debt_equity numeric,
  current_ratio numeric,
  source text default 'MarketPulse',
  updated_at timestamptz not null default now(),
  unique (symbol, report_date)
);

create index if not exists stock_fundamentals_symbol_idx on public.stock_fundamentals (symbol);
create index if not exists stock_fundamentals_date_idx on public.stock_fundamentals (report_date desc);

create table if not exists public.stock_quarterly_results (
  id bigint generated by default as identity primary key,
  symbol text not null references public.stocks(symbol) on delete cascade,
  quarter_date date not null,
  revenue numeric,
  net_profit numeric,
  eps numeric,
  net_margin numeric,
  source text default 'MarketPulse',
  updated_at timestamptz not null default now(),
  unique (symbol, quarter_date)
);

create index if not exists stock_quarterly_symbol_idx on public.stock_quarterly_results (symbol);
create index if not exists stock_quarterly_date_idx on public.stock_quarterly_results (quarter_date desc);

create table if not exists public.stock_price_history (
  symbol text not null references public.stocks(symbol) on delete cascade,
  trade_date date not null,
  open numeric,
  high numeric,
  low numeric,
  close numeric,
  volume bigint,
  source text default 'NSE',
  updated_at timestamptz not null default now(),
  primary key (symbol, trade_date)
);

create index if not exists stock_price_history_date_idx on public.stock_price_history (trade_date desc);
create index if not exists stock_price_history_symbol_date_idx on public.stock_price_history (symbol, trade_date desc);

create or replace function public.set_stock_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists stocks_set_updated_at on public.stocks;
create trigger stocks_set_updated_at before update on public.stocks
for each row execute function public.set_stock_updated_at();

drop trigger if exists stock_quotes_set_updated_at on public.stock_quotes;
create trigger stock_quotes_set_updated_at before update on public.stock_quotes
for each row execute function public.set_stock_updated_at();

drop trigger if exists stock_fundamentals_set_updated_at on public.stock_fundamentals;
create trigger stock_fundamentals_set_updated_at before update on public.stock_fundamentals
for each row execute function public.set_stock_updated_at();

drop trigger if exists stock_quarterly_set_updated_at on public.stock_quarterly_results;
create trigger stock_quarterly_set_updated_at before update on public.stock_quarterly_results
for each row execute function public.set_stock_updated_at();

drop trigger if exists stock_history_set_updated_at on public.stock_price_history;
create trigger stock_history_set_updated_at before update on public.stock_price_history
for each row execute function public.set_stock_updated_at();

alter table public.stocks enable row level security;
alter table public.stock_quotes enable row level security;
alter table public.stock_fundamentals enable row level security;
alter table public.stock_quarterly_results enable row level security;
alter table public.stock_price_history enable row level security;

drop policy if exists "Public can read stocks" on public.stocks;
create policy "Public can read stocks" on public.stocks for select using (true);

drop policy if exists "Public can read stock quotes" on public.stock_quotes;
create policy "Public can read stock quotes" on public.stock_quotes for select using (true);

drop policy if exists "Public can read stock fundamentals" on public.stock_fundamentals;
create policy "Public can read stock fundamentals" on public.stock_fundamentals for select using (true);

drop policy if exists "Public can read quarterly results" on public.stock_quarterly_results;
create policy "Public can read quarterly results" on public.stock_quarterly_results for select using (true);

drop policy if exists "Public can read price history" on public.stock_price_history;
create policy "Public can read price history" on public.stock_price_history for select using (true);

create or replace view public.stock_latest
with (security_invoker = true)
as
select
  s.symbol, s.company_name, s.exchange, s.sector, s.is_fno,
  s.market_cap, s.pe, s.roe, s.roce, s.book_value, s.face_value,
  s.dividend_yield, s.promoters_latest, s.promoters_previous, s.promoters_change,
  q.price, q.previous_close, q.open, q.high, q.low, q.change, q.change_percent,
  q.high_52w, q.low_52w, q.source as quote_source, q.quote_time,
  q.updated_at as price_updated_at
from public.stocks s
left join public.stock_quotes q on q.symbol = s.symbol;
