-- MarketPulse Crypto Signals + Paper Trades
create table if not exists public.crypto_signals (
  id bigint generated by default as identity primary key,
  symbol text not null,
  direction text not null check (direction in ('LONG','SHORT')),
  timeframe text not null default '1h',
  quote text not null default 'USDT',
  entry_price numeric, stop_loss numeric, take_profit numeric, rr numeric,
  score numeric, confidence numeric, rsi numeric, atr numeric, volume_ratio numeric,
  reasons text,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','TRIGGERED','EXPIRED','CANCELLED')),
  created_at timestamptz not null default now(), expires_at timestamptz
);
create index if not exists crypto_signals_status_created_idx on public.crypto_signals(status, created_at desc);
create table if not exists public.crypto_trades (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  signal_id bigint references public.crypto_signals(id) on delete set null,
  symbol text not null, direction text not null check (direction in ('LONG','SHORT')),
  timeframe text, entry_price numeric not null, stop_loss numeric not null, take_profit numeric not null,
  amount_inr numeric not null default 0, leverage numeric not null default 1, rr numeric, score numeric,
  status text not null default 'RUNNING' check (status in ('RUNNING','TP_HIT','SL_HIT','MANUAL_CLOSE','CANCELLED')),
  current_price numeric, close_price numeric, pnl_inr numeric default 0, notes text,
  created_at timestamptz not null default now(), closed_at timestamptz
);
create index if not exists crypto_trades_user_created_idx on public.crypto_trades(user_id, created_at desc);
create index if not exists crypto_trades_running_idx on public.crypto_trades(status, created_at desc);
alter table public.crypto_signals enable row level security;
alter table public.crypto_trades enable row level security;
drop policy if exists "Authenticated users can read crypto signals" on public.crypto_signals;
create policy "Authenticated users can read crypto signals" on public.crypto_signals for select to authenticated using (true);
drop policy if exists "Users can read own crypto trades" on public.crypto_trades;
create policy "Users can read own crypto trades" on public.crypto_trades for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Users can create own crypto trades" on public.crypto_trades;
create policy "Users can create own crypto trades" on public.crypto_trades for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users can update own crypto trades" on public.crypto_trades;
create policy "Users can update own crypto trades" on public.crypto_trades for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can delete own crypto trades" on public.crypto_trades;
create policy "Users can delete own crypto trades" on public.crypto_trades for delete to authenticated using (auth.uid() = user_id);